#### Question 1-

In [12]:
import numpy as np
a=[18, 19, 22, 25, 27, 28, 41, 45, 51, 55]
b=[14, 15, 15, 17, 18, 22, 25, 25, 27, 34]
array1=np.array(a)
array2=np.array(b)

In [21]:
f_value=np.var(array1)/np.var(array2)

In [14]:
f_value

4.387122002085506

In [18]:
p_value = 1-stat.f.cdf(0.05,9,9)
p_value

0.9999353254586377

#### Question 2-

In [15]:
significance_level=0.05
df1=8
df2=6

In [16]:
import scipy.stats as stat

In [17]:
critical_value=stat.f.ppf(q=1-significance_level,dfn=df1,dfd=df2)

In [19]:
critical_value

4.146804162276531

#### Question 3-

In [27]:
from numpy import random

x=random.normal(size=(2,3))
print(x,'\n')
y=random.normal(size=(4,3))
print(y)

[[0.04373497 0.02040906 0.57060789]
 [0.55059259 1.04938823 0.92570352]] 

[[ 0.1879219  -0.61379158  0.44841023]
 [-2.61565222  1.82149193  0.60215437]
 [ 1.15740051 -2.16563219 -0.40179332]
 [-1.88621407  0.2435972   0.66449175]]


In [28]:
variance1=np.var(x)
variance2=np.var(y)
variance_1, variance2

(0.5519715995834394, 1.7366448584373415)

Ho(null hypothesis)=variance are equal

H1(alternate hypothesis)=variance are not equal

In [29]:
f_value=variance1/variance2
f_value

0.08872388668774098

In [32]:
dfn=np.size(x)-1
dfd=np.size(y)-1

In [34]:
p_value=1- stat.f.pdf(.05,dfn=dfn,dfd=dfd)

In [35]:
p_value

0.9057552479229493

#### Question 4-

Ho- variances are different

H1- variances are not different

In [22]:
var1=10
var2=15
f_value=var1/var2

In [23]:
f_value

0.6666666666666666

In [3]:
import numpy as np
import scipy.stats as stat

critical_value=stat.f.ppf(q=1-alpha, dfn=dof,dfd=dof)

In [4]:
critical_value

2.8179304699530863

As, the f-value is less than the critical value, we fail to accept the null hypothesis.

So, the variance of both the populations are not different.

#### Question 5-

Ho- variance of diameter is 0.005

H1- variance of diameter is not 0.005

In [6]:
f_value=0.005/0.006

In [7]:
f_value

0.8333333333333334

In [8]:
dof=24
alpha=0.01

In [9]:
critical_value=stat.f.ppf(1-alpha,dfn=dof,dfd=dof)

In [10]:
critical_value

2.659072104348157

As, the f-value is less than critical value, we fail to accept the
null hypothesis.

Hence, variance of diameter is not 0.005

#### Question 6-

In [42]:
import scipy.stats as stat
import numpy as np
def function(dfn,dfd):
    dfn=dfn
    dfd=dfd
    mean=dfd/(dfd-2)
    variance=(2*dfd**2*(dfn+dfn-2))/(dfn*(dfn-2)**2*(dfn-4))
    return mean,variance
    

Example-

In [44]:
function(9,8)

(1.3333333333333333, 0.9287981859410431)

Question 7-

Ho- Variances are significantly different

H1- Variances are not significantly different

In [6]:
import scipy.stats as stat
S1=25
S2=20
f_value=S1/S2

In [7]:
f_value

1.25

In [8]:
dof1=24
dof2=19
alpha=0.10

In [9]:
critical_value=stat.f.ppf(1-alpha,dfn=dof1,dfd=dof2)

In [10]:
critical_value

1.7873072945308652

As, f-value is less than the critical value, we fail to accpet the null hypothesis.

#### Question 8-

Ho-variance are significantly different

H1- variance are not significantly different

In [31]:
import numpy as np
A=[24, 25, 28, 23, 22, 20, 27]
B=[31, 33, 35, 30, 32, 36]
alpha=0.05
dof1=np.size(A)-1
dof2=np.size(B)-1

In [32]:
var1=np.var(A)
var2=np.var(B)
f_value=var1/var2

In [33]:
f_value

1.496767651159843

In [34]:
critical_value=stat.f.ppf(1-alpha,dfn=dof1,dfd=dof2)

In [35]:
critical_value

4.950288068694318

As, the f-value is less than critical value, we fail to accpet the Null hypothesis.

#### Question 9-

Ho-variance are significantly different

H1- variance are not significantly different

In [30]:
A=[80, 85, 90, 92, 87, 83]
B=[75, 78, 82, 79, 81, 84]

In [ ]:
alpha=0.01
dof1=np.size(A)-1
dof2=np.size(B)-1

In [38]:
var1=np.var(A)
var2=np.var(B)
f_value1=var1/var2

In [39]:
f_value1

1.496767651159843

In [40]:
critical_value=stat.f.ppf(1-alpha,dfn=dof1,dfd=dof2)

In [41]:
critical_value

4.950288068694318

As, the f-value is less than critical value, we fail to accpet the Null hypothesis.