In [4]:
import tensorflow as tf

### Part-1 Theortical Questions

#### Question 1-

1. What are the different data structures used in Tensorflow?. Give some examamples .

Ans. The different data structures used in Tensorflow are:

1. Tensors: Tensors are the fundamental building blocks of TensorFlow, and they represent multi-dimensional arrays of data.
Example:   


In [5]:
vector = tf.constant([1, 2, 3, 4, 5])
print(vector)   

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


2. Variables: Variables are mutable tensors used to store model parameters during training. 
Example:

In [6]:
weights=tf.Variable(tf.random.normal(shape=(2,5)))
print(weights)

<tf.Variable 'Variable:0' shape=(2, 5) dtype=float32, numpy=
array([[ 1.8958393 ,  1.2166234 , -0.06096885, -1.38528   ,  1.2092367 ],
       [-1.006418  , -0.71873224, -0.24546008, -0.89314467,  1.9773018 ]],
      dtype=float32)>


3. SparseTensor: A SparseTensor is a special data structure used for sparse data, where most of the elements are zero. Example

In [7]:
indices=tf.constant([[0,0],[1,1],[2,3]],dtype=tf.int64)
values=tf.constant([1,2,3],dtype=tf.int64)
shape=tf.constant([3,4],dtype=tf.int64)
sparse_tensor=tf.SparseTensor(indices,values,shape)
print(sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 1]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1 2 3], shape=(3,), dtype=int64), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


 4. RaggedTensor: RaggedTensor is used to represent sequences of varying lengths efficiently.  Example: 

In [8]:
rt = tf.ragged.constant([[1, 2], [3], [4, 5, 6]])
print(rt)

<tf.RaggedTensor [[1, 2], [3], [4, 5, 6]]>


#### Question 2-

How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.

TensorFlow Constant:
- A constant in TensorFlow is an immutable data structure. 
- It is mainly used to hold fixed values that remain the same throughout the computation.
- Constants are typically used for model hyperparameters, input data, or any other values that do not change during the training process.
- When you define a constant, its value is fixed, and you cannot update it later during the execution of your TensorFlow graph.

In [9]:
a = tf.constant(5)
b = tf.constant([1, 2, 3])
print(a)
print(b)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


TensorFlow Variable:
- A variable in TensorFlow is a mutable data structure. 
- It can be updated during the execution of the TensorFlow graph.
- Variables are commonly used to represent the learnable parameters of a machine learning model (e.g., weights and biases). 
- During training, the values of these variables are updated based on the optimization algorithm to minimize the loss function.
- Variables are defined with an initial value and can be modified using assignment operations.


In [10]:
weights = tf.Variable(tf.random.normal(shape=(5, 2)))
new_weights = weights * 2
weights.assign(new_weights)
print(weights)

<tf.Variable 'Variable:0' shape=(5, 2) dtype=float32, numpy=
array([[ 2.7424443 ,  2.336153  ],
       [-2.5375967 ,  0.25337926],
       [-1.4353293 ,  1.2336663 ],
       [ 2.3134758 , -0.3486495 ],
       [ 1.8570567 ,  0.7372318 ]], dtype=float32)>


#### Question 3-

Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.

Ans: Matrix Addition:
Matrix addition is performed element-wise on two matrices of the same shape, resulting in a new matrix with the same shape.

     

In [11]:
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])
C = tf.add(A, B)
print(C)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


Matrix Multiplication:

Matrix multiplication is a binary operation that takes two matrices and produces a new matrix by performing a combination 
of dot products between rows and columns of the input matrices.


In [12]:
C = tf.matmul(A, B)
print(C)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [13]:
# Element-wise Operations:
# Element-wise operations are performed independently on each element of the input tensors, without considering their shapes or dimensions. 
C_add = tf.add(A, B)
C_multiply = tf.multiply(A, B)
print(C_add)
print(C_multiply)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


### Part 2- practical Implementation

1.

In [14]:
A=tf.random.normal(shape=(2,2))
print(A)

tf.Tensor(
[[-2.218803    0.27009016]
 [ 0.57644975  0.33010525]], shape=(2, 2), dtype=float32)


2.

In [16]:
B=tf.random.truncated_normal(shape=(2,2))
print(B)

tf.Tensor(
[[-0.6035598  1.5316321]
 [ 1.7087417  0.7615102]], shape=(2, 2), dtype=float32)


3.

In [17]:
C=tf.random.normal(shape=(2,2),mean=3,stddev=0.5)
print(C)

tf.Tensor(
[[3.6273003 3.3600209]
 [2.848317  3.8825922]], shape=(2, 2), dtype=float32)


4.

In [18]:
D=tf.add(A,B)
print(D)

tf.Tensor(
[[-2.8223627  1.8017223]
 [ 2.2851915  1.0916154]], shape=(2, 2), dtype=float32)


5.

In [19]:
E=tf.matmul(C,D)
print(E)

tf.Tensor(
[[-2.5592651 10.2032385]
 [ 0.8334837  9.370173 ]], shape=(2, 2), dtype=float32)


#### Task2-
1. 

In [21]:
F=tf.random.uniform(shape=(3,3))
print(F)

tf.Tensor(
[[0.94446015 0.92389643 0.33968282]
 [0.19591856 0.09173    0.8671242 ]
 [0.967618   0.16627908 0.26166987]], shape=(3, 3), dtype=float32)


2.

In [22]:
G=tf.transpose(F)
print(G)

tf.Tensor(
[[0.94446015 0.19591856 0.967618  ]
 [0.92389643 0.09173    0.16627908]
 [0.33968282 0.8671242  0.26166987]], shape=(3, 3), dtype=float32)


3.

In [23]:
H=tf.math.exp(F)
print(H)

tf.Tensor(
[[2.5714247 2.5190868 1.404502 ]
 [1.2164278 1.0960689 2.3800564]
 [2.6316683 1.1809026 1.2990977]], shape=(3, 3), dtype=float32)


4.

In [24]:
I=tf.concat((F,G),axis=1)
print(I)

tf.Tensor(
[[0.94446015 0.92389643 0.33968282 0.94446015 0.19591856 0.967618  ]
 [0.19591856 0.09173    0.8671242  0.92389643 0.09173    0.16627908]
 [0.967618   0.16627908 0.26166987 0.33968282 0.8671242  0.26166987]], shape=(3, 6), dtype=float32)


5.

In [25]:
J=tf.concat((F,H),axis=0)
print(J)

tf.Tensor(
[[0.94446015 0.92389643 0.33968282]
 [0.19591856 0.09173    0.8671242 ]
 [0.967618   0.16627908 0.26166987]
 [2.5714247  2.5190868  1.404502  ]
 [1.2164278  1.0960689  2.3800564 ]
 [2.6316683  1.1809026  1.2990977 ]], shape=(6, 3), dtype=float32)
