#### Question 1-

Ordinal Encoding-> 
1. used to encode the input feature.
2. returns a single column of integers(0 to n-1 categories) per feature.
3. can fit multiple column at the same time
4. preserves the order of categorical data by assigning rank

label Encoding->
1. used to encode the output/target feature.
2. returns a single column of integers(0 to n_labels -1) per feature.
3. can only fit a vector of samples
4. does not preserves the order of the categorical data

Example:
1. If we have to assign numerical values to names of students in a class(ascending order), we use Label Encoding.
2. If we want to assign numerical values to say low as 0, medium as 1 and high as 2 , where we can manually assign these values to the categorical features , we use the ordinal encoding.

#### Question 2-

Target guided encoding-
In this technique we will take help of our target variable to encode the categorical data .
Example:

In [1]:
import pandas as pd

#create a sample dataframe with a categorical variable and a target variable
df=pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]
})

In [2]:
df

city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [7]:
#calculating the mean of each city
mean_price=df.groupby('city')['price'].mean()

In [8]:
mean_price

city
London      150.0
New York    190.0
Paris       310.0
Tokyo       250.0
Name: price, dtype: float64

In [9]:
## We can replace each city with it's mean price
df['city_encode']=df['city'].map(mean_price)

In [10]:
df

city  price  city_encode
0  New York    200        190.0
1    London    150        150.0
2     Paris    300        310.0
3     Tokyo    250        250.0
4  New York    180        190.0
5     Paris    320        310.0

#### Question 3-

Covariance is a measure of the relationship between two random variables and to what extent, they change together. Or we can say, in other words, it defines the changes between the two variables, such that change in one variable is equal to change in another variable.

The covariance formula is similar to the formula for correlation and deals with the calculation of data points from the average value in a dataset. For example, the covariance between two random variables X and Y can be calculated using the following formula (for population):

Cov(X,Y)= sigma[(Xi-Xmean)(Yi-Ymean)]/n

n=number of sample points

#### Question 4-

In [13]:
import pandas as pd

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
df=pd.DataFrame({
    'color':['red','green','blue'],
    'size':['small','medium','large'],
    'material':['wood','metal','plastic']
})

In [16]:
df

color    size material
0    red   small     wood
1  green  medium    metal
2   blue   large  plastic

In [17]:
encoder=LabelEncoder()

In [22]:
for i in df.columns:
    print(encoder.fit_transform(df[i]))
    

[2 1 0]
[2 1 0]
[2 0 1]


So based on the aplhabetical order, the Label Encoder has assigned numerical values to each category of the Categorical features.

#### Question 5-

In [23]:
df=pd.DataFrame({
    'age':[42,30,69],
    'income':[1000,2000,3000],
    'education_level':[2,3,1]
})

In [24]:
df

age  income  education_level
0   42    1000                2
1   30    2000                3
2   69    3000                1

In [28]:
import numpy as np
np.cov(df)

array([[ 319228.        ,  646891.        ,  967270.        ],
       [ 646891.        , 1311606.33333333, 1960818.16666667],
       [ 967270.        , 1960818.16666667, 2931564.33333333]])

#### Question 6-

For Gender-> I would use OneHot Encoding because as the categories are binary i.e male or female only two columns would be created , one for each category.

For Education Level--> We can use Ordinal encoding based on the rank of the education level of a person.
We can assign 1 to PhD, 2 to masters, 3 to bachelors, and 4 to High Schhol level.

For Employment status--> We can use Label Encoding, as the order of the category is not required here.  


#### Question 7-

In [33]:
df=pd.DataFrame({
    'Temperature':[40,50,45,36,33],
    'Humidity':[0.74,0.58,0.99,0.68,0.66],
    'weather':['sunny','cloudy','rainy','sunny','rainy'],
    'wind_direction':['north','south','east','west','south']
})

In [36]:
df

Temperature  Humidity weather wind_direction
0           40      0.74   sunny          north
1           50      0.58  cloudy          south
2           45      0.99   rainy           east
3           36      0.68   sunny           west
4           33      0.66   rainy          south

In [37]:
encoder=LabelEncoder()

In [38]:
encoder.fit_transform(df['weather'])

array([2, 0, 1, 2, 1])

In [39]:
df['weather']=df['weather'].replace(['sunny','cloudy','rainy'],[2,0,1])

In [40]:
df

Temperature  Humidity  weather wind_direction
0           40      0.74        2          north
1           50      0.58        0          south
2           45      0.99        1           east
3           36      0.68        2           west
4           33      0.66        1          south

In [41]:
encoder.fit_transform(df['wind_direction'])

array([1, 2, 0, 3, 2])

In [42]:
df['wind_direction']=df['wind_direction'].replace(['north','south','east','west'],[1,2,0,3])

In [43]:
df

Temperature  Humidity  weather  wind_direction
0           40      0.74        2               1
1           50      0.58        0               2
2           45      0.99        1               0
3           36      0.68        2               3
4           33      0.66        1               2

In [44]:
np.cov(df)

array([[375.75023333, 475.8223    , 429.63231667, 330.57746667,
        307.87043333],
       [475.8223    , 604.39076667, 544.29688333, 419.5036    ,
        390.82903333],
       [429.63231667, 544.29688333, 491.655025  , 377.67913333,
        351.99668333],
       [330.57746667, 419.5036    , 377.67913333, 291.71893333,
        271.48386667],
       [307.87043333, 390.82903333, 351.99668333, 271.48386667,
        252.81556667]])