In [2]:
import numpy as np

In [3]:
list_=['1','2','3','4','5']

In [4]:
array_list=np.array(object=list_)

In [5]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

#### Question 1-

In [6]:
array_list.dtype

dtype('<U1')

In [7]:
type(list_)

list

The data types of list_ is list, while the data type of array_list is '<U1' which stands for unsigned 8-bit integer. It basically describes how the bytes in the fix-size block of memory corresponding to an array item should be interpreted. Here, each block of memory assigned to the array item is assigned an 8-byte memory.

#### Question 2-

In [8]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [10]:
for i in array_list:
    print(i.dtype)

<U1
<U1
<U1
<U1
<U1


In [11]:
array_list=np.array(object=list_, dtype=int)

In [14]:
array_list

array([1, 2, 3, 4, 5])

In [15]:
array_list.dtype

dtype('int64')

Yes, now there is a difference in data types of the elements present in list_ and array_list.
The data type of eac variable in list_ is string, while the data type of each variable in the array_list is integer.

In [16]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [17]:
for i in array_list:
    print(i.dtype)

int64
int64
int64
int64
int64


In [18]:
import numpy as np

In [19]:
num_list=[[1,2,3],[4,5,6]]

In [21]:
num_array=np.array(object=num_list)

#### Question 4-

In [23]:
num_array.size

6

In [24]:
num_array.shape

(2, 3)

#### Question 5-

In [27]:
a=np.zeros((3,3))

In [29]:
np.matrix(a)

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

#### Question 6-

In [31]:
b=np.eye(5)

In [32]:
np.matrix(b)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])